### ISSUE TITLE
Testing/CI only happens for one version of python

### ISSUE THREAD

**Issue by ianepreston** [ianepreston/stats_can#14]
Would be cool to use tox or something to check against different versions of python, maybe different library versions too.

**Comment by chritter** [comment]
Hi @ianepreston, I would welcome checks beyond 3.7. I suppose Python 3 only support and one can remove the Travis yml statement for Python 2.7?

**Comment by ianepreston** [comment]
@chritter, yes. I would expect this only works in 3.x. If you know an easy way to add multiple version tests I would welcome a PR. I might add it myself eventually but honestly it's pretty low in my queue of projects, so it likely wouldn't be any time soon.

**Comment by ianepreston** [comment]
Fixed this long ago and forgot to close
