### ISSUE TITLE
conda package is bloated

### ISSUE THREAD

**Issue by ianepreston** [ianepreston/stats_can#19]
Somewhere between 2.2.1 and 2.2.2 I added 9MB. Need to tune my build process because it shouldn't be nearly that big. I suspect it's that I'm including files from my test suite

**Comment by chritter** [comment]
Hi @ianepreston, Yes, the last table added in `test_files` in tests is rather large. To avoid too large Conda packages and to allow users to run the test suite via the package there are two options I am aware:

- Keep the test files as part of the Conda package and reduce the size of the 9MB table so much as to still allow the test of weird dates
-  Remove `test_files` data directory from the Conda build process. When`pytest` is run from the Conda package the missing `test_files` directory is automatically downloaded from the repo (using git commit version of package), e.g. via `conftest.py`.

Which way do you prefer? I could provide a PR.

**Comment by ianepreston** [comment]
@chritter, that would be great! I think the second option makes more sense for the package. I don't see why a user would need to run the test suite if they've just installed it expecting a library. A PR would be excellent. Would you mind adding a version bump as well? I think dropping the package size by an order of magnitude (as removing the test files will) is worth a bump to 2.2.3. The version is set in ```stats_can/stats_can/__init__.py```

**Comment by chritter** [comment]
@ianepreston Issue can be closed as it was addressed in the PR.

**Comment by ianepreston** [comment]
Thanks for the reminder. Fixed #19
