### ISSUE TITLE
Please do not use upper bounds for dependencies 🙏 

### ISSUE THREAD

**Issue by psarka** [ianepreston/stats_can#324]
Your dependencies are all upper bounded, could you please remove those upper bounds? Today I'm blocked from using pandas 2.0 together with your library :(

Currently your dependencies are:

```
[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = "^2.20"
h5py = ">=2.10,<4.0"
tables = "^3.6"
tqdm = "^4.48"
pandas = ">=1.1,<3.0"
importlib-metadata = "^6.0.0"
```

I think you should just use

```
[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = ">=2.20"
h5py = ">=2.10"
tables = ">=3.6"
tqdm = ">=4.48"
pandas = ">=1.1"
importlib-metadata = ">=6.0.0"
```

(And also this [blog post](https://iscinumpy.dev/post/bound-version-constraints/) for the reference. TLDR: upper bounds == bad, makes you work more & release every time your deps upgrade, breaks everyone with no recourse).

**Comment by ianepreston** [comment]
That seems like a reasonable suggestion. Do you want to submit a PR?

**Comment by psarka** [comment]
Could you, please, publish 2.5.2 on pypi? :)

**Comment by ianepreston** [comment]
Yup, sorry. My publish action was only looking for changes in `src` so I had to update it to include `pyproject.toml` as well and bump to `2.5.3` to trigger a release. It should be there now

**Comment by psarka** [comment]
Thank you 👏
