### ISSUE TITLE
test failed: test_vectors_to_df_by_release

### ISSUE THREAD

**Issue by azimj** [ianepreston/stats_can#55]
One test failed for me (test_vectors_to_df_by_release`:

I am on Ubuntu 20.04 with the default version of Python (v3.8.5) with git head @ commit: 16dbaff2' on branch `master`  with pandas 1.1.5.

Here are some relevant lines from the log output of running `pytest`

```
KeyError: 'refPer'

pandas/_libs/hashtable_class_helper.pxi:4562: KeyError

The above exception was the direct cause of the following exception:

    @pytest.mark.vcr()
    def test_vectors_to_df_by_release():
        """Test one vector to df method."""
>       r = stats_can.sc.vectors_to_df(
            vs, start_release_date=dt.date(2018, 1, 1), end_release_date=dt.date(2018, 5, 1)
        )

test_stats_can.py:169: 
```
And a second line from the log that might be of relevance is

```
 ???
E   KeyError: 'refPer'

pandas/_libs/hashtable_class_helper.pxi:1683: KeyError

The above exception was the direct cause of the following exception:

    @pytest.mark.vcr()
    def test_vectors_to_df_by_release():
        """Test one vector to df method."""
>       r = stats_can.sc.vectors_to_df(
            vs, start_release_date=dt.date(2018, 1, 1), end_release_date=dt.date(2018, 5, 1)
        )

tests/test_stats_can.py:169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/stats_can/sc.py:607: in vectors_to_df
    pd.DataFrame(vec["vectorDataPoint"])

```

Let me know if you need more information about my environment.

**Comment by ianepreston** [comment]
Hi Azim,

I can reproduce this issue in some situations so it's not an issue with your setup. I'm not totally sure what's causing it yet though. I'll get a fix up as soon as I can but I don't know if I'll have time to work on it soon.

**Comment by azimj** [comment]
Hi Ian,

No hurry, I can just skip that test as I fix the test my new code for using `pathlib` broke.

**Comment by ianepreston** [comment]
Hi Azim,

So the issue was that the second vector in that test is from the Consumer Price Index. Statistics Canada rebased the series to December 2020, which means that there are no longer any data points released in that period. I'm working on a branch that will allow the test to pass and handle that logic
