### ISSUE TITLE
odd file names

### ISSUE THREAD

**Issue by azimj** [ianepreston/stats_can#60]
I'm not sure what's going on with commit `0d5e3ebf` but this file is causing git checkout issues:

`tests/cassettes/test_missing_data_from_h5[table_from_h5-23100216-Downloading and loading table_23100216\n].yaml` 

maybe it is the **\n** in the file name that windows doesn't like.

Anyway, just thought I'd mention it.

**Comment by ianepreston** [comment]
I'm guessing it's the \n. Can you tell me what the error is exactly?

**Comment by azimj** [comment]
Here is the message when cloning into clean working directory:

PS D:\home\azimj\tmp> git clone https://github.com/ianepreston/stats_can.git
Cloning into 'stats_can'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 1130 (delta 37), reused 26 (delta 17), pack-reused 1066 eceiving objects:  99% (1119/1130), 77.38 MiB | 715.00 KiB/s
Receiving objects: 100% (1130/1130), 77.57 MiB | 842.00 KiB/s, done.
Resolving deltas: 100% (665/665), done.
error: invalid path 'tests/cassettes/test_missing_data_from_h5[table_from_h5-23100216-Downloading and loading table_23100216\n].yaml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ianepreston** [comment]
You're probably right that it's a Windows issue. I don't think I can control that file name, it's generated by VCR. Any chance you can use WSL as a development environment? Things tend to go smoothly in a Linux/Mac environment compared to Windows.

**Comment by azimj** [comment]
I do have WSL and an Ubuntu install that I work on. Yeah, the package doesn't install on Windows. I cannot install one of your  dependencies (`tables`)  on Windows. I will focus on fixing my pathlib code under WSL. Thanks for checking.

**Comment by ianepreston** [comment]
@azimj are you ok if I close this issue?
