### ISSUE TITLE
Parse dates fails on certain tables

### ISSUE THREAD

**Issue by ianepreston** [ianepreston/stats_can#7]
During design and test of this app I focused on monthly tables. Because of this the code makes assumptions about the format of the REF_DATE column that cause it to break on the ```parse_dates``` function call. @AttyXY, do you remember the number for the table where you identified this bug?

**Comment by AttyXY** [comment]
Table number: 13-10-0805-02
Link: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310080502
