### ISSUE TITLE
pip install stats-can not working?

### ISSUE THREAD

**Issue by kalhors** [ianepreston/stats_can#77]
Hi @ianepreston 

I am not sure if it is a mistake from my end or not. I tried to install the package via cmd window, but it gives me dependency error. Please check below. What should I do to get it installed?

ERROR: Cannot install stats-can==2.3.3, stats-can==2.3.4, stats-can==2.3.5, stats-can==2.4.0 and stats-can==2.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    stats-can 2.5.0 depends on tables<4.0.0 and >=3.6.1
    stats-can 2.4.0 depends on tables<4.0.0 and >=3.6.1
    stats-can 2.3.5 depends on tables<4.0.0 and >=3.6.1
    stats-can 2.3.4 depends on tables<4.0.0 and >=3.6.1
    stats-can 2.3.3 depends on tables<4.0.0 and >=3.6.1

Here is a screenshot of my cmd window:

<img width="671" alt="Screenshot 2021-03-08 21 52 44" src="https://user-images.githubusercontent.com/80301877/110416117-bb225980-8058-11eb-824f-48d21a7fd32d.png">

**Comment by kalhors** [comment]
Following the last message, I also tried installing the package through Settings --> Python Interpreter, but received the same error message. Could it be that I am using Windows while the package can be installed only in Mac? Thanks for your time.

**Comment by ianepreston** [comment]
@kalhors tables is a little tricky to install on Windows, that's probably why you're getting the error. Are you looking to use stats_can in a project or contribute to it? If you just want to use it in a project I'd recommend using conda to manage your environments, it makes it much easier to install dependencies like tables in Windows. If you're looking to contribute to the development consider using WSL, as supporting python development directly in Windows is challenging. See #60 for someone having a similar issue in that regard.

**Comment by kalhors** [comment]
Thank you for your reply. Yes I am going to use it for a project. I can't contribute yet because I am not as much experienced yet. 
Anyway, I followed your advice and tried to install the package using Anaconda3. But I failed this time with a different error message that the package does not exist. What is causing the problem in your opinion?

Here is a screen shot:

<img width="672" alt="Screenshot 2021-03-09 21 36 55" src="https://user-images.githubusercontent.com/80301877/110573542-10c23900-8121-11eb-9e1d-98005c41b951.png">

**Comment by ianepreston** [comment]
You have to get it through conda forge, not the base conda channel. Add "-c conda-forge" to your command

**Comment by kalhors** [comment]
Hi there,

Yes it worked. Thanks so much. I missed the conda forge command when reading the help file. I realized it later. 

As for the contribution, I would love to contribute. But for now I am just learning this process, as I am a newbie in API world. In the meantime, if you think there is something I can do let me know.   

Thanks again for your help,
Cheers,
S

**Comment by ianepreston** [comment]
No worries, you're also more than welcome to just use the package of course.
